### ISSUE TITLE
简体转换繁体当前 dict 的 map 不合适

### ISSUE THREAD

**Issue by huacnlee** [golandscape/sat#4]
我发现简体 -> 繁体的时候：

`繁体` 这个字会转成 `緐體`，常见的用法是 `繁體`，比如 Twitter 的语言设置下拉：

<img width="508" alt="截屏2021-06-02 23 55 44" src="https://user-images.githubusercontent.com/5518/120514577-0782f880-c400-11eb-832d-d05719c9b815.png">

从我目前查到的资料来看 `繁` 字是有多种用法 `繁`, `緐` 都可以。

----

似乎当前的问题是 dict 的 maps 关系就一个，所以 sat 不得不选用了 `緐`，否则繁体转简体，这个字就对应不出来。

这么看来要更好的结果，需要 **简繁** 和 **繁简** 用不同字典

**Comment by lascape** [comment]
解决这个问题可以使用自定义的词库，使用多个字段转换实例
